import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session, status } = useSession();
  const [pageData, setPageData] = useState({
    url: "",
    title: "",
  });

  useEffect(() => {
    chrome.tabs &&
      chrome.tabs.query(
        { active: true, currentWindow: true },
        (tabs: any[]) => {
          const url = tabs[0].url;
          const title = tabs[0].title;
          setPageData({ url, title });
        }
      );

    console.log(setPageData);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Savelink</h1>
          <>
            {status === "loading" && (
              <div>
                <p>Logging you in :)</p>
              </div>
            )}

            {status === "authenticated" ? (
              <>
                <p> Logged in as : {session.user?.email} </p>

                <div className={styles.login}>
                  <button onClick={() => signOut()}>Sign Out</button>
                </div>
              </>
            ) : (
              <>
                <p>Youre not logged in yet. Click below to sign in :)</p>
                <p>{pageData.title}</p>
                <p>{pageData.url}</p>
                <p>Should show, idk</p>
                <div className={styles.login}>
                  <button onClick={() => signIn("google")}>Sign In</button>
                </div>
              </>
            )}
          </>
        </div>
      </main>
    </>
  );
}
